### ISSUE TITLE
Bad transaction date !? Sakia 0.32.4

### ISSUE THREAD

**Issue by galuel** [duniter/sakia#751]
When launching Sakia 0.32.4, blockchain synchronises. Tentative to send money during this results in account balance reduced with a transaction date older than date of the day (probably date of the blockchain at the moment of synchronisation ?!).

This can only be viewed after closing and launching Sakia again...

Account where money should be viewable appear to have not received the amount, so did the transaction work or not ?!

All this result in something very unclear...

**Comment by Insoleet** [comment]
There is a bug with Sakia 0.32.4 when sending money between accounts. It is fixed in 0.32.5.

**Comment by galuel** [comment]
The transaction is still present in Sakia, but seems refused in Cesium, but it appears 2 "change TX" in Cesium, inscribed in blockchain relative to that TX, and 8 "CHAINED" in Sakia, so it is difficult to know and understand what is happening really...

What is happening !? What to do ?

**Comment by Insoleet** [comment]
You should probably reinitialize Sakia to see what is really present in the blockchain.

I had a lot of fears when I got the same exact bug, but dont worry, no money is lost... It's only not displayed correctly.
